demo/urls.py
from django.urls import path

from demo import views

app_name = "demo"
urlpatterns = [
    path('',views.demohome,name="demohome"),
    path('update/<int:id>/',views.updatedemo,name="updatedemo"),
]

dynamic_formset/urls.py
from django.urls import path

from dynamic_formset.views import index,create_contact

app_name = "dynamic_formset"

urlpatterns = [
    path('',index,name='index'),
    path('create-contact',create_contact,name='create-contact'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dynamic_formset.urls',namespace="dynamic_formset")),
    path('demo',include('demo.urls',namespace='demo')),
]

demo/models.py
from django.db import models

class DemoModel(models.Model):
    name = models.CharField(max_length=255)
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    

dynamic_formset/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=255)
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

htmx/models.py
from django.db import models

# Create your models here.

demo/forms.py
from django import forms

from demo.models import DemoModel

class DemoModelForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

dynamic_formset/forms.py
from django import forms

from dynamic_formset.models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name','title')
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'title':forms.TextInput(attrs={'class':'form-control'}),
        }

demo/views.py
from django.shortcuts import render,redirect

from demo.forms import DemoModelForm
from demo.models import DemoModel

def demohome(request):
    demomodels = DemoModel.objects.all()
    if request.method == 'POST':
        form = DemoModelForm(request.POST or None)
        if form.is_valid():
            # name = form.cleaned_data['name']
            # title = form.cleaned_data['title']
            name = request.POST.get('name')
            title = request.POST.get('title')
            DemoModel(name = name, title = title).save()
            return redirect('demo:demohome')
    else:
        form = DemoModelForm()
    context = {'form':form,'demomodels':demomodels}
    return render(request,'demo.html',context)


def updatedemo(request,id):
    demomodels = DemoModel.objects.get(id = id)
    if request.method == 'POST':
        form = DemoModelForm(request.POST or None)
        if form.is_valid():
            demomodels.name = form.cleaned_data['name']
            demomodels.title = form.cleaned_data['title']
            # print(f"------------{name}-----------{title}")
            # demomodels(name = name, title = title).save()
            demomodels.save()
            return redirect('demo:demohome')
    context = {'demomodels':demomodels}
    return render(request,'update.html',context)

dynamic_formset/views.py
from django.shortcuts import render,redirect

from dynamic_formset.forms import ContactForm
from dynamic_formset.models import Contact

def index(request):
    context = {'form':ContactForm(),'contacts':Contact.objects.all()}
    return render(request,'home.html',context)

def create_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST or None)
        if form.is_valid():
            contact = form.save()
            context = {'contact':contact}
            return render(request,'contact.html',context)
    return render(request,'form.html',{'form':ContactForm})

htmx/views.py
from django.shortcuts import render

# Create your views here.

demo/templates/demo.html
{% extends 'base.html' %}
{% block content %}
<h1>this is demo html</h1>

<div>
    {% for demomodel in demomodels %}
        <p>{{demomodel.name}}-{{demomodel.title}}</p><span><a href="{% url 'demo:updatedemo' demomodel.id %}">edit</a></span>
    {% endfor %}
</div><hr>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">submit</button>
</form>
{% endblock %}

demo/templates/update.html
{% extends 'base.html' %}
{% block content %}
<h1>this is upate html</h1>
<form method="post">
    {% csrf_token %}
    <label>Name:</label>
    <input class="form-control" type="text" placeholder="{{demomodels.name}}" name="name"><br>
    <label>title:</label>
    <input class="form-control" type="text" placeholder="{{demomodels.title}}" name="title">
    <button class="btn btn-primary" type="submit">submit</button>
</form>
{% endblock %}

dynamic_formset/templates/contact.html
<li>{{ contact.name}} - {{ contact.title }}</li>

dynamic_formset/templates/form.html
<form hx-post="{% url 'dynamic_formset:create-contact' %}" hx-target="#contact-list" hx-swap="beforeend" hx-on="htmx:afterRequest: this.remove()" hx-trigger="click from:#submit-all" action="">
    {% csrf_token %}
    <div class="row">
        <div class="col-4 col-md-3">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name }}
        </div>
        <div class="col-4 col-md-3">
            <label for="{{ form.name.id_for_label }}">{{ form.name.title }}</label>
            {{ form.title }}
        </div>

        <div class="col-3 align-self-end">
            <button type="button" class="btn btn-danger" hx-on="click: this.closest('form').remove()">Cancel</button>
        </div>
        <!-- <div class="col-3 align-self-end">
            <button class="btn btn-primary" type="submit">submit</button>
        </div> -->
    </div>
</form>

dynamic_formset/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>dynamic formset django</h1>

<div id="contact-forms">
    {% include 'form.html' %}
</div>

<div class="my-4">
    <button type="button" class="btn btn-success me-2" hx-get="{% url 'dynamic_formset:create-contact' %}" hx-target="#contact-forms" hx-swap="beforeend">+ Add contact</button>
    <button type="button" class="btn btn-primary" id="submit-all">submit all</button>
</div>

<ul id="contact-list">
    {% for contact in contacts %}
        {% include 'contact.html' %}
    {% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dynamic formset</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://unpkg.com/htmx.org@1.9.6"></script>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>